export const VC_GREEN = '#1F6B2E';
export const VC_GREEN_LIGHT = '#3D8C42';
export const VC_GREEN_BG = '#E8F5E9';

export const CAT_ICONS = {
  IOGURTE: '🥛',
  'WHEY IOGURTE': '💪',
  'WHEY SHAKE': '🥤',
  SOBREMESA: '🍮',
  QUEIJO: '🧀',
  PASTAS: '🧈',
  CREME: '🥛',
};

export const CAT_ORDER = [
  'IOGURTE',
  'WHEY IOGURTE',
  'WHEY SHAKE',
  'SOBREMESA',
  'QUEIJO',
  'PASTAS',
  'CREME',
];

// Order of sections in the export (matches Verde Campo template order)
export const SECAO_ORDER = [
  'LINHA KIDS',
  'IOGURTE DESNATADO NATURAL',
  'IOGURTES NATURAL WHEY 140G',
  'IOGURTES NATURAL WHEY 170G',
  'IOGURTES NATURAL WHEY 250G',
  'IOGURTES NATURAL WHEY 500G',
  'IOGURTES INTEGRAL 2 INGR',
  'IOGURTES DESN 2 INGR',
  'SOBREMESA (CAIXA COM 12 UNIDADES)',
  'IOGURTES LACFREE 140G (CAIXA COM 12 UNIDADES)',
  'IOGURTES LACFREE 170G',
  'IOGURTES LACFREE 500G',
  'IOG TRADICIONAL BATIDO 500G',
  'IOG A2 INTEGRAL 500G',
  'IOGURTES KEFIR 500G',
  'IOG TRADICIONAL MORANGO',
  'IOGURTES PROBIÓTICOS 170G',
  'IOGURTES PROBIÓTICOS 500G',
  'IOGURTES PROBIÓTICOS TRIPLO ZERO 500G',
  'CREMES 500G',
  'PASTAS',
  'QUEIJO FRESCAL',
  'QUEIJO MUSSARELA',
  'QUEIJO PRATO',
  'QUEIJO PADRÃO',
  'SHAKES WHEY 14',
  'SHAKES WHEY 15',
];
